[build]
builder = "dockerfile"

[deploy]
startCommand = "npx prisma db push --accept-data-loss && node index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PORT = "8080"
NODE_ENV = "production"